[sftp-corsario]
enabled  = true
port     = 22
filter   = sshd
logpath  = /var/log/corsario-sftp/auth.log
backend  = auto
maxretry = 3
findtime = 10m
bantime  = 1h
action   = docker-user[name=sftp-corsario, port=22, protocol=tcp]
